/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * JHistogram.java
 *
 * Created on Oct 28, 2010, 2:15:46 PM
 */

package image;

import java.util.Random;
import javax.swing.JFrame;
import javax.swing.SwingUtilities;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.statistics.HistogramDataset;
import org.jfree.data.xy.IntervalXYDataset;

/**
 *
 * @author apple
 */
public class JHistogram extends javax.swing.JPanel {
      HistogramDataset dataset         =   new HistogramDataset();
      JFreeChart chart                 =   null;
      ChartPanel chartPanel            =   null;
      int numberOfbeans                =    51;
    public JHistogram( 
            double  []data,
            String seriresName,
            String plotTitle,
            String xlabel,
            String ylabel) {
         initComponents();
         dataset.addSeries(seriresName, data, numberOfbeans);
         chart           = createChart(dataset, plotTitle, xlabel, ylabel);
         chartPanel      = new ChartPanel(chart);
         chartPanel.setPreferredSize(new java.awt.Dimension(800, 600));
         chartPanel.setMouseZoomable(true, false);
         add(chartPanel);
    }
    private JFreeChart createChart(
            IntervalXYDataset dataset,
            String title,
            String xlabel,
            String ylabel
            ) {
          JFreeChart achart = ChartFactory.createHistogram(
             null,
             xlabel,
             ylabel,
             dataset,
             PlotOrientation.VERTICAL,
             true,
             false,
             false
         );
         achart.getXYPlot().setForegroundAlpha(0.75f);
         return achart;
     }



    public static JHistogram showHistogram(
            double []data,
            String sertiesName,
            String title,
            String xlabel,
            String ylabel){
        JHistogram histogram = new JHistogram(data,  sertiesName, title, xlabel,ylabel);

        try{
            JFrame frame = new JFrame(title);
            frame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);

            //Add contents to the window.
            frame.add(histogram );

          //  histogram.populateHistogram(data);


            //Display the window.
            frame.pack();
            frame.setVisible(true);
        }
        catch (Exception e){
            e.printStackTrace();
        }
        finally{
            return histogram ;
        }


    }

    private static void createAndShowGUI() {
       double [] data   = {3,4,5,2,3,3,3,4,5,56,34,34,32,23,23.3};
       showHistogram(data, "testSet", "Title", null, null);
    }
    public static void main(String[] args) {
        //Schedule a job for the event dispatch thread:
        //creating and showing this application's GUI.
        SwingUtilities.invokeLater(new Runnable() {
            public void run() {
                createAndShowGUI();
            }
        });
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setLayout(new java.awt.BorderLayout());
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

}
