/*
 * PlotASCII.java
 *
 * Created on August 20, 2007, 2:43 PM
 */

package utilities;
import utilities.GraphGUI;
import java.awt.*;
import java.awt.event.*;

import javax.swing.*;
import javax.swing.event.*;
import javax.swing.text.*;
import javax.swing.table.*;

import java.text.*;
import java.util.*;
import java.io.*;
 
import org.jfree.chart.*;
import org.jfree.chart.plot.*;
import org.jfree.data.*;
import org.jfree.chart.axis.*;
import org.jfree.data.general.*;
import org.jfree.data.xy.*;
import org.jfree.ui.*;
import org.jfree.chart.renderer.xy.*;
import org.jfree.chart.entity.*;
import org.jfree.chart.annotations.*;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.chart.renderer.category.*;
import org.jfree.chart.title.*;
import org.jfree.data.category.*;


import static java.lang.Math.*;
public class PlotASCII extends javax.swing.JPanel {
    
 
    public PlotASCII (double [] X, double [] Y) {
          if(X != null && Y != null){
            dataX  = new double [ X.length];
            dataY  = new double [ Y.length];
            for (int i = 0; i < X.length; i++) {
                dataX[i]    =   X[i];
                dataY[i]    =   Y[i];
            }           
        }
       
        initComponents ();
        XYSeries series = GraphGUI.createXYSeries  (dataX, dataY,"");
        xydataset       = new XYSeriesCollection (series);
        chart           = ChartFactory.createXYLineChart(
                             null, null, null,xydataset, 
                             PlotOrientation.VERTICAL,
                             true, true, true );
        chartPanel= new ChartPanel(chart);
        this.add (chartPanel);
    }
    public PlotASCII (File file, int x_indx, int y_indx) {
        this.file = file;
        try {
            dataX  = IO.nASCI2double(file.getAbsolutePath (), x_indx);
            dataY  = IO.nASCI2double(file.getAbsolutePath (), y_indx);
            doPlot( dataX, dataY );
        } catch (FileNotFoundException ex) {
            ex.printStackTrace();
        } catch (IOException ex) {
            ex.printStackTrace();
        }
        
        initComponents ();
        this.add (chartPanel);
    }


    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {

        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.X_AXIS));

    }// </editor-fold>//GEN-END:initComponents
    public  void doPlot(double [] x , double [] y){
        XYSeries series = GraphGUI.createXYSeries  (x, y,"");
        xydataset       = new XYSeriesCollection (series);
        chart           = ChartFactory.createXYLineChart(
                             null, null, null,xydataset, 
                             PlotOrientation.VERTICAL,
                             true, true, true );
        chartPanel= new ChartPanel(chart);
    }  
    public  void addToPlot(double [] x , double [] y){
        XYSeries series = GraphGUI.createXYSeries  (x, y,"");
        xydataset.addSeries (series);
        chart           = ChartFactory.createXYLineChart(
                             null, null, null,xydataset, 
                             PlotOrientation.VERTICAL,
                             true, true, true );
        chartPanel= new ChartPanel(chart);
    }    
    public  void showGUI (JFrame frame) {   
       if (this.isShowing ()) return;
       if (frame == null ) {
          frame = new JFrame ();
          frame.setDefaultCloseOperation (JFrame.DISPOSE_ON_CLOSE);
       }
       frame.setContentPane (this);
       frame.pack ();
       frame.setVisible (true);
    } 
    public  void showGUI (JPanel pane) {   
       if (pane == null) return;
       pane.removeAll();
       pane.add (chartPanel);
       pane.revalidate();
    } 
    private static void createAndShowGUI () {
        //Disable boldface controls.
        UIManager.put ("swing.boldMetal", Boolean.FALSE);
        
        //Create and set up the window.
        JFrame frame = new JFrame ("FID Binary Viewer");
        frame.setDefaultCloseOperation (JFrame.EXIT_ON_CLOSE);
     
        //Create and set up the content pane.
        PlotASCII  newContentPane = new PlotASCII( new File("dat.01"),1,2 );
            
           
        newContentPane.setOpaque (true); //content panes must be opaque
        frame.setContentPane (newContentPane);
        
        //Display the window.
        frame.pack ();
        frame.setVisible (true);
    }
    public  static void main (String[] args) {
      
        //Schedule a job for the event-dispatching thread:
        //creating and showing this application's GUI.
        javax.swing.SwingUtilities.invokeLater (new Runnable () {
            public void run () {
                createAndShowGUI ();
            }
        });
 
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    private double dataX [];
    private double dataY [];
    private File file;
    private XYSeriesCollection  xydataset;
    private ChartPanel chartPanel;
    private JFreeChart chart;  
     private static final long serialVersionUID  = 7526472294622776147L;
}
