/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * JSetFourierWeighting.java
 *
 * Created on Feb 23, 2009, 9:43:41 AM
 */

package fid;
import java.awt.MouseInfo;
/**
 *
 * @author apple
 */
public class JSetFourierWeighting extends javax.swing.JDialog {

    private JSetFourierWeighting(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    private static final long serialVersionUID                  =   7526372295622516127L;
    public static final int MAXIMUM_LB_SLIDER                   =   100;
    public static final int MINIMUM_LB_SLIDER                   =   0;



    private static  JSetFourierWeighting  instance              =   null;
    private FidViewable viewer                                  =   FidViewer.getInstance();

    private static  JSetFourierWeighting getInstance( ) {
      if(instance == null) {
         instance = new JSetFourierWeighting(null, true);

      }

      return instance;
   }
    public static   JSetFourierWeighting showDialog(FidViewable aviewer ){
        getInstance().setViewer(aviewer);
        getInstance( ).updateFromViewer();
        getInstance( ).setLocation(MouseInfo.getPointerInfo().getLocation());
        getInstance( ).setVisible(true);

       return instance;
    }

      public void updateFromViewer(){
        FidReader freader       =   viewer.getFidReader();
        float procparLB         =   freader.getProcpar().getLb();
        float userLB            =   freader.getUserLb();

        getProcparLbFormattedTextField().setValue(procparLB);
        getUserLbFormattedTextField ().setValue(userLB);
   }



    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        reset_ = new javax.swing.JButton();
        close_ = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        userLB_jrb = new javax.swing.JFormattedTextField();
        procparLB_lbl = new javax.swing.JLabel();
        procparLB_jrb = new javax.swing.JFormattedTextField();
        userLB_lbl = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        incr10 = new javax.swing.JButton();
        incr30 = new javax.swing.JButton();
        incr100 = new javax.swing.JButton();
        dec10 = new javax.swing.JButton();
        dec30 = new javax.swing.JButton();
        dec100 = new javax.swing.JButton();

        FormListener formListener = new FormListener();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Set LB"); // NOI18N
        setForeground(new java.awt.Color(255, 0, 0));
        addWindowListener(formListener);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(153, 153, 153), new java.awt.Color(102, 102, 102), new java.awt.Color(51, 51, 51), new java.awt.Color(102, 102, 102)));
        jPanel1.setName("jPanel1"); // NOI18N

        reset_.setFont(new java.awt.Font("Lucida Grande", 1, 15)); // NOI18N
        reset_.setText("RESET");
        reset_.setName("reset_"); // NOI18N
        reset_.addActionListener(formListener);

        close_.setFont(new java.awt.Font("Lucida Grande", 1, 15)); // NOI18N
        close_.setText("CLOSE");
        close_.setName("close_"); // NOI18N
        close_.addActionListener(formListener);

        jPanel2.setName("jPanel2"); // NOI18N
        jPanel2.setLayout(new java.awt.GridBagLayout());

        userLB_jrb.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, null, new java.awt.Color(51, 51, 51)));
        userLB_jrb.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("###0.###"))));
        userLB_jrb.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        userLB_jrb.setFont(new java.awt.Font("Lucida Grande", 1, 16));
        userLB_jrb.setName("userLB_jrb"); // NOI18N
        userLB_jrb.addPropertyChangeListener(formListener);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(0, 12, 3, 0);
        jPanel2.add(userLB_jrb, gridBagConstraints);

        procparLB_lbl.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        procparLB_lbl.setText("Procpar LB");
        procparLB_lbl.setName("procparLB_lbl"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanel2.add(procparLB_lbl, gridBagConstraints);

        procparLB_jrb.setEditable(false);
        procparLB_jrb.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.0##"))));
        procparLB_jrb.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        procparLB_jrb.setEnabled(false);
        procparLB_jrb.setFocusLostBehavior(javax.swing.JFormattedTextField.REVERT);
        procparLB_jrb.setFont(new java.awt.Font("Lucida Grande", 1, 16));
        procparLB_jrb.setName("procparLB_jrb"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 2.0;
        gridBagConstraints.insets = new java.awt.Insets(3, 12, 0, 0);
        jPanel2.add(procparLB_jrb, gridBagConstraints);

        userLB_lbl.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        userLB_lbl.setText("Set LB to");
        userLB_lbl.setName("userLB_lbl"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanel2.add(userLB_lbl, gridBagConstraints);

        jPanel3.setName("jPanel3"); // NOI18N
        jPanel3.setLayout(new java.awt.GridLayout(2, 3, 4, 6));

        incr10.setText("+ 10%");
        incr10.setName("incr10"); // NOI18N
        incr10.addActionListener(formListener);
        jPanel3.add(incr10);

        incr30.setText("+ 30%");
        incr30.setName("incr30"); // NOI18N
        incr30.addActionListener(formListener);
        jPanel3.add(incr30);

        incr100.setText("+ 100%");
        incr100.setName("incr100"); // NOI18N
        incr100.addActionListener(formListener);
        jPanel3.add(incr100);

        dec10.setText("- 10%");
        dec10.setName("dec10"); // NOI18N
        dec10.addActionListener(formListener);
        jPanel3.add(dec10);

        dec30.setText("- 30%");
        dec30.setName("dec30"); // NOI18N
        dec30.addActionListener(formListener);
        jPanel3.add(dec30);

        dec100.setText("- 100%");
        dec100.setName("dec100"); // NOI18N
        dec100.addActionListener(formListener);
        jPanel3.add(dec100);

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .add(20, 20, 20)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(jPanel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(reset_, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 114, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(close_, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 104, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(jPanel3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(new java.awt.Component[] {jPanel2, jPanel3}, org.jdesktop.layout.GroupLayout.HORIZONTAL);

        jPanel1Layout.linkSize(new java.awt.Component[] {close_, reset_}, org.jdesktop.layout.GroupLayout.HORIZONTAL);

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jPanel3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(18, 18, 18)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(reset_, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                    .add(close_))
                .addContainerGap())
        );

        jPanel1Layout.linkSize(new java.awt.Component[] {close_, reset_}, org.jdesktop.layout.GroupLayout.VERTICAL);

        getContentPane().add(jPanel1);

        pack();
    }

    // Code for dispatching events from components to event handlers.

    private class FormListener implements java.awt.event.ActionListener, java.awt.event.WindowListener, java.beans.PropertyChangeListener {
        FormListener() {}
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            if (evt.getSource() == reset_) {
                JSetFourierWeighting.this.reset_ActionPerformed(evt);
            }
            else if (evt.getSource() == close_) {
                JSetFourierWeighting.this.close_ActionPerformed(evt);
            }
            else if (evt.getSource() == incr10) {
                JSetFourierWeighting.this.incr10ActionPerformed(evt);
            }
            else if (evt.getSource() == incr30) {
                JSetFourierWeighting.this.incr30ActionPerformed(evt);
            }
            else if (evt.getSource() == incr100) {
                JSetFourierWeighting.this.incr100ActionPerformed(evt);
            }
            else if (evt.getSource() == dec10) {
                JSetFourierWeighting.this.dec10ActionPerformed(evt);
            }
            else if (evt.getSource() == dec30) {
                JSetFourierWeighting.this.dec30ActionPerformed(evt);
            }
            else if (evt.getSource() == dec100) {
                JSetFourierWeighting.this.dec100ActionPerformed(evt);
            }
        }

        public void windowActivated(java.awt.event.WindowEvent evt) {
        }

        public void windowClosed(java.awt.event.WindowEvent evt) {
        }

        public void windowClosing(java.awt.event.WindowEvent evt) {
            if (evt.getSource() == JSetFourierWeighting.this) {
                JSetFourierWeighting.this.formWindowClosing(evt);
            }
        }

        public void windowDeactivated(java.awt.event.WindowEvent evt) {
        }

        public void windowDeiconified(java.awt.event.WindowEvent evt) {
        }

        public void windowIconified(java.awt.event.WindowEvent evt) {
        }

        public void windowOpened(java.awt.event.WindowEvent evt) {
        }

        public void propertyChange(java.beans.PropertyChangeEvent evt) {
            if (evt.getSource() == userLB_jrb) {
                JSetFourierWeighting.this.userLB_jrbPropertyChange(evt);
            }
        }
    }// </editor-fold>//GEN-END:initComponents

    private void userLB_jrbPropertyChange (java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_userLB_jrbPropertyChange
        if (this.isVisible() == false){return;}
        if (evt.getPropertyName ().equals ("value")){
                updateViewer ();
        }
}//GEN-LAST:event_userLB_jrbPropertyChange
    private void reset_ActionPerformed (java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reset_ActionPerformed
        float lb                = getViewer().getFidReader ().getProcpar ().getLb ();
         getUserLbFormattedTextField ().setValue (lb);
    }//GEN-LAST:event_reset_ActionPerformed
    private void close_ActionPerformed (java.awt.event.ActionEvent evt) {//GEN-FIRST:event_close_ActionPerformed
        close ();
}//GEN-LAST:event_close_ActionPerformed
    private void formWindowClosing (java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
         close ();
    }//GEN-LAST:event_formWindowClosing
    private void incr10ActionPerformed (java.awt.event.ActionEvent evt) {//GEN-FIRST:event_incr10ActionPerformed
       double val =  ((Number)getUserLbFormattedTextField ().getValue ()).doubleValue();
        if(val == 0) {
                getUserLbFormattedTextField ().setValue (1);
         }
         else{
       
                getUserLbFormattedTextField ().setValue (val*1.1);
         }
    }//GEN-LAST:event_incr10ActionPerformed
    private void incr30ActionPerformed (java.awt.event.ActionEvent evt) {//GEN-FIRST:event_incr30ActionPerformed
        double val =  ((Number)getUserLbFormattedTextField ().getValue ()).doubleValue();
         if(val == 0) {
                getUserLbFormattedTextField ().setValue (1);
         }
         else{
            getUserLbFormattedTextField ().setValue (val*1.3);
         }
}//GEN-LAST:event_incr30ActionPerformed
    private void incr100ActionPerformed (java.awt.event.ActionEvent evt) {//GEN-FIRST:event_incr100ActionPerformed
         double val =  ((Number)getUserLbFormattedTextField ().getValue ()).doubleValue();
         if(val == 0) {
                getUserLbFormattedTextField ().setValue (1);
         }
         else{
             getUserLbFormattedTextField ().setValue (val*2);
         }

}//GEN-LAST:event_incr100ActionPerformed
    private void dec10ActionPerformed (java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dec10ActionPerformed
      double val =  ((Number)getUserLbFormattedTextField ().getValue ()).doubleValue();
      getUserLbFormattedTextField ().setValue (val*0.9);
}//GEN-LAST:event_dec10ActionPerformed
    private void dec30ActionPerformed (java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dec30ActionPerformed
        double val =  ((Number)getUserLbFormattedTextField ().getValue ()).doubleValue();
        getUserLbFormattedTextField ().setValue (val*0.7);
}//GEN-LAST:event_dec30ActionPerformed
    private void dec100ActionPerformed (java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dec100ActionPerformed
         double val =  ((Number)getUserLbFormattedTextField ().getValue ()).doubleValue();
        getUserLbFormattedTextField ().setValue (val*0.5);
}//GEN-LAST:event_dec100ActionPerformed


   private void updateViewer(){
         float userLB =  ((Number)getUserLbFormattedTextField ().getValue ()).floatValue();
         if (userLB <= 0)   {
                    userLB = 0;
                    getUserLbFormattedTextField ().setValue (0);
          }

         FidReader freader =  viewer.getFidReader();
         if (userLB  != freader.getUserLb()){
            freader.setUserLb(userLB);
            freader.computeSpectralData(true);
            FidIO.storeToDisk(freader.getFidDescriptor(), viewer.getFidDescriptorFile());
            viewer.updatePlot();
         }
    }

    public void close(){
        updateViewer();
        setVisible(false);
    }
  
    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JSetFourierWeighting dialog = new JSetFourierWeighting(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton close_;
    private javax.swing.JButton dec10;
    private javax.swing.JButton dec100;
    private javax.swing.JButton dec30;
    private javax.swing.JButton incr10;
    private javax.swing.JButton incr100;
    private javax.swing.JButton incr30;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JFormattedTextField procparLB_jrb;
    private javax.swing.JLabel procparLB_lbl;
    private javax.swing.JButton reset_;
    private javax.swing.JFormattedTextField userLB_jrb;
    private javax.swing.JLabel userLB_lbl;
    // End of variables declaration//GEN-END:variables

    public javax.swing.JFormattedTextField  getProcparLbFormattedTextField() {
        return procparLB_jrb;
    }
    public javax.swing.JFormattedTextField  getUserLbFormattedTextField () {
        return userLB_jrb;
    }
  

    public FidViewable      getViewer () {
        return viewer;
    }
    public void             setViewer ( FidViewable viewer ) {
        this.viewer = viewer;
    }

}
