/*
 * JCleanJobRequest.java
 *
 * Created on April 1, 2008, 12:05 PM
 */

package interfacebeans;

import run.JRun;
import bayes.BayesManager;
import java.awt.MouseInfo;

/**
 *
 * @author  apple
 */
public class JCleanJobRequest extends javax.swing.JDialog {
    
    /** Creates new form JCleanJobRequest */
    public JCleanJobRequest (java.awt.Frame parent, boolean modal) {
        super (parent, modal);
        
        initComponents ();
        
       //JRun.getAndUpdateStatus();
       status_tf.setText(JRun.getStatus().getName());
       jobID_tf.setText(JRun.getJobID());

    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        ok_btn = new javax.swing.JButton();
        cancel_btn = new javax.swing.JButton();
        status_label = new javax.swing.JLabel();
        jobID_label = new javax.swing.JLabel();
        status_tf = new javax.swing.JTextField();
        jobID_tf = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();

        FormListener formListener = new FormListener();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("HANDLE SUBMITTED JOB"); // NOI18N
        setAlwaysOnTop(true);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);

        ok_btn.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        ok_btn.setText("Yes");
        ok_btn.addActionListener(formListener);

        cancel_btn.setFont(new java.awt.Font("Lucida Grande", 0, 14));
        cancel_btn.setText("Cancel");

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${isDeleteJob}"), cancel_btn, org.jdesktop.beansbinding.BeanProperty.create("selected"));
        bindingGroup.addBinding(binding);

        cancel_btn.addActionListener(formListener);

        status_label.setFont(new java.awt.Font("Lucida Grande", 1, 14));
        status_label.setText("Job status");

        jobID_label.setFont(new java.awt.Font("Lucida Grande", 1, 14));
        jobID_label.setText("Job ID");

        status_tf.setEditable(false);
        status_tf.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        status_tf.setMinimumSize(new java.awt.Dimension(105, 22));
        status_tf.setRequestFocusEnabled(false);

        jobID_tf.setEditable(false);
        jobID_tf.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jobID_tf.setMinimumSize(new java.awt.Dimension(105, 22));
        jobID_tf.setRequestFocusEnabled(false);

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 1, 14));
        jLabel3.setText("Switch to a new package");
        jLabel3.setToolTipText("<html>Selecting yes, will delete<br>\ncurrently submitted job<br>\nand will switch to a new package</html>\n"); // NOI18N

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jobID_label)
                            .add(ok_btn, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 87, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(status_label))
                        .add(32, 32, 32)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(cancel_btn)
                            .add(jobID_tf, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(status_tf, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 90, Short.MAX_VALUE)))
                    .add(jLabel3))
                .addContainerGap(53, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
        );

        layout.linkSize(new java.awt.Component[] {cancel_btn, jobID_label, jobID_tf, ok_btn, status_label, status_tf}, org.jdesktop.layout.GroupLayout.HORIZONTAL);

        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(13, 13, 13)
                .add(jLabel3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 25, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(status_label)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jobID_label, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 15, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(ok_btn))
                    .add(layout.createSequentialGroup()
                        .add(status_tf, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jobID_tf, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(cancel_btn)))
                .addContainerGap())
        );

        layout.linkSize(new java.awt.Component[] {jobID_label, jobID_tf, status_label, status_tf}, org.jdesktop.layout.GroupLayout.VERTICAL);

        bindingGroup.bind();

        pack();
    }

    // Code for dispatching events from components to event handlers.

    private class FormListener implements java.awt.event.ActionListener {
        FormListener() {}
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            if (evt.getSource() == ok_btn) {
                JCleanJobRequest.this.ok_btnActionPerformed(evt);
            }
            else if (evt.getSource() == cancel_btn) {
                JCleanJobRequest.this.cancel_btnActionPerformed(evt);
            }
        }
    }// </editor-fold>//GEN-END:initComponents

    private void ok_btnActionPerformed (java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ok_btnActionPerformed
        isDeleteJob = true;
        deleteLastSubmittedJob();
        setVisible(false);
    }//GEN-LAST:event_ok_btnActionPerformed

    private void cancel_btnActionPerformed (java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancel_btnActionPerformed
        isDeleteJob = false;
        setVisible(false);
    }//GEN-LAST:event_cancel_btnActionPerformed
    
    public static void deleteLastSubmittedJob(){
        if (JRun.getStatus() == null) { return;}
        JRun.canceJob();
    }
    /**
     * @param args the command line arguments
     */
    public static void main (String args[]) {
        java.awt.EventQueue.invokeLater (new Runnable () {
            public void run () {
                JCleanJobRequest dialog = new JCleanJobRequest (new javax.swing.JFrame (), true);
                dialog.addWindowListener (new java.awt.event.WindowAdapter () {
                    public void windowClosing (java.awt.event.WindowEvent e) {
                        System.exit (0);
                    }
                });
                dialog.setVisible (true);
            }
        });
    }


    public static boolean cleanSubmittedJobAndSwitchPackage(){

         String id      = JRun.getJobID();
         System.out.println("In cleanSubmittedJobAndSwitchPackage job id "+id );
         // if there are no currently submitted jobs
         // do nothing.
         if ( id == null ) {
             return true;
         }
         else {
            JCleanJobRequest cleanJob   = new JCleanJobRequest(null, true);
            java.awt.Point point        = MouseInfo.getPointerInfo().getLocation();
            cleanJob.setLocation (point);
            cleanJob.setVisible(true);
            cleanJob.dispose();
            return JCleanJobRequest.isDeleteJob;
         }
   }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancel_btn;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jobID_label;
    private javax.swing.JTextField jobID_tf;
    private javax.swing.JButton ok_btn;
    private javax.swing.JLabel status_label;
    private javax.swing.JTextField status_tf;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
    public  static boolean isDeleteJob  = true;
    private static final long serialVersionUID      = 7526472295622576143L;

}
