/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * JFileSelector.java
 *
 * Created on Jul 27, 2009, 9:57:11 AM
 */

package interfacebeans;
import java.io.File;
import java.awt.Color;
import java.awt.Component;
import java.awt.Font;
import javax.swing.*;
/**
 *
 * @author apple
 */
public class JFileSelector extends javax.swing.JDialog implements bayes.ApplicationConstants {
   // private File [] files         =   new File[0] ;
    
    private File [] files         =   new File []{
      new File ("1"), new File ("2"), new File ("3"), new File ("4"), new File ("5"), new File ("6"),new File ("7"),
      new File ("8"), new File ("9"), new File ("10"),new File ("11"), new File ("12"), new File ("13"),
      new File ("14"), new File ("15"), new File ("10"),new File ("11"), new File ("12"), new File ("13"),
       new File ("14"), new File ("15"), new File ("15"),new File ("17"), new File ("18"), new File ("13")
    } ;
    

    /** Creates new form JFileSelector */
    public JFileSelector(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    public JFileSelector(File [] files,java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        this.files = files;
        initComponents();
    }

    public static  JFileSelector  showJFileSelector(File [] files ){
        JFileSelector fselector = new JFileSelector(files,null, true);
        fselector.setVisible(true);

        return fselector;
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        fileJList = new javax.swing.JList();
        buttonPane = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Select file to display"); // NOI18N
        setAlwaysOnTop(true);
        setLocationByPlatform(true);
        setModal(true);
        setResizable(false);

        jScrollPane1.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(153, 153, 153), new java.awt.Color(204, 204, 204)));
        jScrollPane1.setPreferredSize(new java.awt.Dimension(400, 400));

        fileJList.setFont(new java.awt.Font("Lucida Grande", 0, 14));
        fileJList.setModel(generateDefaultListModel());
        fileJList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        fileJList.setCellRenderer(new  CustomCellRenderer());
        fileJList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fileJListMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(fileJList);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jButton1.setText("Close");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        buttonPane.add(jButton1);

        javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance(bayes.BayesApp.class).getContext().getActionMap(JFileSelector.class, this);
        jButton2.setAction(actionMap.get("hideDialog")); // NOI18N
        buttonPane.add(jButton2);

        getContentPane().add(buttonPane, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void fileJListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fileJListMouseClicked
       if (evt.getClickCount() > 1){
            hideDialog();
       }
    }//GEN-LAST:event_fileJListMouseClicked

    /**
    * @param args the command line arguments
    */
    public   DefaultListModel    generateDefaultListModel(){
        DefaultListModel dm     =   new DefaultListModel();
        if (files == null) {return dm;}

        for (int i = 0; i < files.length; i++) {
            dm.add(i, files[i]);

        }

        return dm;
    }
    public   File getSelectedFile(){
        return (File)this.fileJList.getSelectedValue();
    }


    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JFileSelector dialog = new JFileSelector(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel buttonPane;
    private javax.swing.JList fileJList;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    public File[] getFiles() {
        return files;
    }

    public void setFiles(File[] files) {
        this.files = files;
    }





     class CustomCellRenderer extends JLabel implements ListCellRenderer {
        private  final Color HIGHLIGHT_COLOR        = new Color(0, 0, 128);
        private  final long serialVersionUID        = 7526472295628576147L;
        public CustomCellRenderer() {
        setOpaque(true);
        Font font   = new Font("Dialog", 1,16);
        this.setFont(font);
   //setIconTextGap(12);
  }


        public Component getListCellRendererComponent(JList list, Object value,
        int index, boolean isSelected, boolean cellHasFocus) {
        File entry = (File) value;
        String pad = "  ";
        setText(pad  + entry.getName());
        this.setHorizontalAlignment(SwingConstants.LEADING);

   if (isSelected) {
      setBackground(HIGHLIGHT_COLOR);
      setForeground(Color.white);
    } else {
      setBackground(Color.white);
      setForeground(Color.black);
    }
    return this;
  }
 }

                @org.jdesktop.application.Action
    public void hideDialog() {
            this.setVisible(false);
    }
}
