/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Dicom2ImgDialog.java
 *
 * Created on Apr 15, 2009, 3:01:19 PM
 */

package load;
import java.awt.*;
import utilities.*;
import javax.swing.*;
import java.util.*;
/**
 *
 * @author apple
 */
public class Dicom2ImgDialog extends javax.swing.JDialog {
    private static   Dicom2ImgDialog    instance       =   null;
    private boolean canceled                              =   false;
    private boolean arrayed                               =   false;
    private  Dicom2ImgConverter converter                 =   new Dicom2ImgConverter();

    private Dicom2ImgDialog  (java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    private static  Dicom2ImgDialog   getInstance( ) {
      if(instance == null) {
         instance = new Dicom2ImgDialog (null, true);
      }

      return instance;
   }
    public static   Dicom2ImgDialog   showDialog(Dicom2ImgConverter converter  ){
       Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
       int x                =    screenSize.width/2- 200;
       int y                =    screenSize.height/2- 200;

       return showDialog(converter, x,y);

    }
    public static   Dicom2ImgDialog   showDialog(Dicom2ImgConverter converter, int x, int y ){
        //update settings

         // be default values are not active unless "set" button is pressed
         getInstance().setCanceled(true);


         // assign converter
         getInstance().setConverter(converter);

         // reset parameters
         DefaultComboBoxModel  serModel = new  DefaultComboBoxModel (converter.getSeriesList().toArray());
         getInstance().getSeriesNumberComboBox ().setModel(serModel);
         if( converter.getSeriesList().isEmpty()){
            getInstance().getSeriesNumberComboBox ().setEnabled(false);
         }
         else{
            getInstance().getSeriesNumberComboBox ().setEnabled(true);
         }
        
         DefaultComboBoxModel  studyModel = new  DefaultComboBoxModel (converter.getStudyList().toArray());
         getInstance().getStudyIDComboBox ().setModel(studyModel);
         if(converter.getStudyList().isEmpty()){
            getInstance().getStudyIDComboBox ().setEnabled(false);
         }
         else{
              getInstance().getStudyIDComboBox ().setEnabled(true);
         }



         // show Preferences
        getInstance( ).setLocation(new java.awt.Point(x,y));
        getInstance( ).setVisible(true);
       return instance;
    }
    public          Dicom2ImgDialog   hideDialog( ){
                    setVisible(false);
       return instance;
    }
    /** Creates new form Dicom2ImgDialog */

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cancelButton = new javax.swing.JButton();
        setButton = new javax.swing.JButton();
        studyIDComboBox = new javax.swing.JComboBox();
        seriesNumberComboBox = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        FormListener formListener = new FormListener();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Dicom Loading Dialog"); // NOI18N
        setResizable(false);

        cancelButton.setText("CANCEL");
        cancelButton.setName("cancelButton"); // NOI18N
        cancelButton.setOpaque(true);
        cancelButton.addActionListener(formListener);

        setButton.setText("OK");
        setButton.setName("setButton"); // NOI18N
        setButton.setOpaque(true);
        setButton.addActionListener(formListener);

        studyIDComboBox.setToolTipText("<html> Study ID from dicom file headers.\n</html>"); // NOI18N
        studyIDComboBox.setName("studyIDComboBox"); // NOI18N

        seriesNumberComboBox.setToolTipText("<html> Series number from dicom file headers.\n</html>"); // NOI18N
        seriesNumberComboBox.setName("seriesNumberComboBox"); // NOI18N

        jLabel1.setText("Study ID");
        jLabel1.setName("jLabel1"); // NOI18N

        jLabel2.setText("Series Number");
        jLabel2.setName("jLabel2"); // NOI18N

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(cancelButton)
                    .add(jLabel2)
                    .add(jLabel1))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(setButton)
                    .add(seriesNumberComboBox, 0, 96, Short.MAX_VALUE)
                    .add(studyIDComboBox, 0, 96, Short.MAX_VALUE))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(new java.awt.Component[] {cancelButton, jLabel1, jLabel2, seriesNumberComboBox, setButton, studyIDComboBox}, org.jdesktop.layout.GroupLayout.HORIZONTAL);

        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.CENTER)
                    .add(jLabel1)
                    .add(studyIDComboBox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.CENTER)
                    .add(jLabel2)
                    .add(seriesNumberComboBox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(18, 18, 18)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(cancelButton)
                    .add(setButton, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        layout.linkSize(new java.awt.Component[] {cancelButton, setButton}, org.jdesktop.layout.GroupLayout.VERTICAL);

        pack();
    }

    // Code for dispatching events from components to event handlers.

    private class FormListener implements java.awt.event.ActionListener {
        FormListener() {}
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            if (evt.getSource() == cancelButton) {
                Dicom2ImgDialog.this.cancelButtonActionPerformed(evt);
            }
            else if (evt.getSource() == setButton) {
                Dicom2ImgDialog.this.setButtonActionPerformed(evt);
            }
        }
    }// </editor-fold>//GEN-END:initComponents

    private void cancelButtonActionPerformed (java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        setCanceled(true);
        hideDialog ( );
}//GEN-LAST:event_cancelButtonActionPerformed

    private void setButtonActionPerformed (java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setButtonActionPerformed
            
        if (getStudyIDComboBox ().getSelectedItem() != null){
             String studyID = (String)getStudyIDComboBox ().getSelectedItem();
        this.getConverter().setStudyID(studyID);
        
        }

        if (getSeriesNumberComboBox().getSelectedItem() != null){
            String seriesNumber = (String)getSeriesNumberComboBox ().getSelectedItem();
          this.getConverter().setSeriesNumber(seriesNumber);
        }
        
        
        setCanceled(false);


            hideDialog ( );
}//GEN-LAST:event_setButtonActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Dicom2ImgDialog dialog = new Dicom2ImgDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JComboBox seriesNumberComboBox;
    private javax.swing.JButton setButton;
    private javax.swing.JComboBox studyIDComboBox;
    // End of variables declaration//GEN-END:variables
    public javax.swing.JComboBox getSeriesNumberComboBox () {
        return seriesNumberComboBox;
    }
    public javax.swing.JComboBox getStudyIDComboBox () {
        return studyIDComboBox;
    }

    public boolean isCanceled () {
        return canceled;
    }
    public void setCanceled ( boolean canceled ) {
        this.canceled = canceled;
    }


    public static boolean isDialogCanceled () {
        return getInstance().isCanceled();
    }

    public Dicom2ImgConverter getConverter () {
        return converter;
    }
    public void setConverter (Dicom2ImgConverter converter ) {
        this.converter = converter;
    }

    
}
